### ISSUE TITLE
Errors with Node.JS.  Unable to create the esp32 projects (both Win / Ubuntu)

### ISSUE THREAD

**Issue by mightylastingcode** [Mair/create-esp32-app#9]
I need some help.  I have a problem using your Node JS app today (both Window 10 and Ubuntu 20.04 LTS).  It cannot create the project.  In the project folder, there is no file.  I did not have any issue last Friday on Window 10.    Thank you for any help or comment you can provide.

Best regards,
Michael

Windows 10
=========
C:\Users\mikel\Documents\esp_idf\esp32\idf420_examples\peripherals>npx create-esp32-app
npx: installed 424 in 19.384s
IDF_PATH env var set! using C:\esp\esp-idf
IDF_TOOLS_PATH env var set! using C:\esp\tools\.espressif
? Project Name ledc_vsc
? Select directory to ESP-IDF C:\esp\esp-idf
? Select directory to espressif Tools (Xtensa tools[.espressif] directory]) C:\esp\tools\.espressif
? Use C++ (default is c [press Enter]) No
? Select additional sample code blinky [example: blink led], debug [debug cfg files], menuconfig [example: config menu
 with idf.py menuconfig]
answers {
  projectName: 'ledc_vsc',
  iDFPath: 'C:\\esp\\esp-idf',
  toolsPath: 'C:\\esp\\tools\\.espressif',
  isCpp: false,
  pythonDir: null,
  Additions: [ 'blinky', 'Debug', 'menuconfig' ]
}
Generating Template with name"ledc_vsc"
(node:3968) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of null
    at generateTemplateModel (C:\Users\mikel\AppData\Roaming\npm-cache\_npx\3968\node_modules\create-esp32-app\index.js:204:41)
    at generate (C:\Users\mikel\AppData\Roaming\npm-cache\_npx\3968\node_modules\create-esp32-app\index.js:150:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3968) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3968) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Ubuntu 20.04 LTS
===============

michael@michael-SVE141190X:~/esp/esp_idf_v420_projects/examples/peripherals$ npx create-esp32-app
npx: installed 424 in 14.789s
IDF_PATH env var not set
IDF_TOOLS_PATH env var not set
? Project Name gio_vsc
? Select directory to ESP-IDF /home/michael/esp/esp-idf
? Select directory to espressif Tools (Xtensa tools[.espressif] directory]) /home/michael/.espressif
? Use C++ (default is c [press Enter]) No
(node:15405) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir '/home/michael/.npm/_npx/15405/lib/node_modules/create-esp32-app/additions'
    at Object.readdirSync (fs.js:790:3)
    at getAdditions (/home/michael/.npm/_npx/15405/lib/node_modules/create-esp32-app/index.js:85:27)
    at generate (/home/michael/.npm/_npx/15405/lib/node_modules/create-esp32-app/index.js:113:29)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:15405) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:15405) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by kristofmulier** [comment]
I have a similar issue on `Ubuntu 20.04.2 LTS`:

```sh
kristof@kristof-ubuntu:~/esp$ npx create-esp32-app
npx: installed 424 in 12.428s
IDF_PATH env var not set
IDF_TOOLS_PATH env var not set
? Project Name test1
? Select directory to ESP-IDF /home/kristof/esp/esp-idf
? Select directory to espressif Tools (Xtensa tools[.espressif] directory]) /hom
e/kristof/esp/tools/.espressif
? Use C++ (default is c [press Enter]) No
(node:11168) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir '/home/kristof/.npm/_npx/11168/lib/node_modules/create-esp32-app/additions'
    at Object.readdirSync (fs.js:854:3)
    at getAdditions (/home/kristof/.npm/_npx/11168/lib/node_modules/create-esp32-app/index.js:85:27)
    at generate (/home/kristof/.npm/_npx/11168/lib/node_modules/create-esp32-app/index.js:113:29)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:11168) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11168) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

These are my `node` and `npm` versions:

```sh
kristof@kristof-ubuntu:~/esp$ node --version
v12.14.1
kristof@kristof-ubuntu:~/esp$ npm --version
6.13.4
```
Please help, because I would really love to continue the course. Now I'm pretty much stuck.

**Comment by lennymlopes** [comment]
Same problem on macOS Big Sur 11.2.3 (Intel)

```
 ~/esp > npx create-esp32-app
IDF_PATH env var set! using /Users/lennymlopes/esp/esp-idf
IDF_TOOLS_PATH env var set! using /Users/lennymlopes/.espressif
? Project Name test
? Select directory to ESP-IDF /Users/lennymlopes/esp/esp-idf
? Select directory to espressif Tools (Xtensa tools[.espressif] directory]) /Users/lennymlopes/.espressif
? Use C++ (default is c [press Enter]) No
? Select additional sample code 
answers {
  projectName: 'test',
  iDFPath: '/Users/lennymlopes/esp/esp-idf',
  toolsPath: '/Users/lennymlopes/.espressif',
  isCpp: false,
  pythonDir: null,
  Additions: []
}
Generating Template with name"test"
(node:8230) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of null
    at generateTemplateModel (/Users/lennymlopes/.npm/_npx/cdbecf361f8464be/node_modules/create-esp32-app/index.js:204:41)
    at generate (/Users/lennymlopes/.npm/_npx/cdbecf361f8464be/node_modules/create-esp32-app/index.js:150:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8230) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8230) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```


 ~/esp > node --version
v14.9.0
 ~/esp > npm --version
7.10.0
```

**Comment by RizwanHamid** [comment]
I am facing the same problem on ubuntu 20.04.

**Comment by Mair** [comment]
Hi Guys, Sorry for the late response. Issue should now be resolved with the latest update
